Delete docs/img/management-upgrade-assistant-7.0.png:Zone.Identifier
error: invalid path 'docs/img/management-upgrade-assistant-7.0.png:Zone.Identifier'
occurs because the file name includes :Zone.Identifier, which is an invalid character for file paths on Windows. Windows does not allow colons (:) in file or folder names, except as part of drive letters (e.g., C:\).